### ISSUE TITLE
[bilibili]解析异常 https://www.bilibili.com/video/av19759891

### ISSUE THREAD

**Issue by luhy118** [iawia002/annie#153]
`D:\go_workspace\annie>annie -i https://www.bilibili.com/video/av19759891
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.Download(0xc04200c2d0, 0x29)
        C:/Users/admin/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:141 +0x813
main.download(0xc04200c2d0, 0x29)
        C:/Users/admin/go/src/github.com/iawia002/annie/main.go:56 +0x79f
main.main()
        C:/Users/admin/go/src/github.com/iawia002/annie/main.go:121 +0xe7`

**Comment by luhy118** [comment]
打开此URL实则跳转到https://www.bilibili.com/bangumi/play/ep197757/
