### ISSUE TITLE
TW爱奇艺是否有支持？

### ISSUE THREAD

**Issue by qwervbnm** [iawia002/annie#180]
平台：       win10 x64
测试链接：http://tw.iqiyi.com/v_19rr1hrvo0.html

挂TW全局代理，网页能够正常播放该链接视频，使用最新版annie，报错如下

>annie -d http://tw.iqiyi.com/v_19rr1hrvo0.html

[36mannie[0m: version [34m0.7.5[0m, A fast, simple and clean video downloader.

URL:         http://tw.iqiyi.com/v_19rr1hrvo0.html
Method:      GET
Headers:     http.Header{
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"},
    "Referer":         {"https://www.iqiyi.com"},
}
Status Code: 200
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Iqiyi(0xc042086030, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/iqiyi.go:96 +0xded
main.download(0xc042086030, 0x25)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:72 +0x537
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:129 +0xe7

**Comment by iawia002** [comment]
下个版本修复

```console
annie -s 127.0.0.1:1080 -i http://tw.iqiyi.com/v_19rr1hrvo0.html

 Site:      爱奇艺 iqiyi.com
 Title:     工作細胞：第1集 肺炎鏈球菌
 Type:      video
 Streams:   # All available quality
     [21]  -------------------
     Quality:         896x504
     Size:            122.87 MiB (128843356 Bytes)
     # download with: annie -f 21 "URL"
...
```

有一点我必须要强调的是，你必须要给 annie 加上 TW 的代理才行，HTTP 或者 Socks5 代理，https://github.com/iawia002/annie#proxy

**Comment by qwervbnm** [comment]
@iawia002 感谢修复，实测最高能解析到720P分辨率，但是

```
>annie -s 127.0.0.1:1080 -i https://tw.iqiyi.com/v_19rr1v8lok.html

 Site:      爱奇艺 iqiyi.com
 Title:     異世界魔王與召喚少女的奴隸魔術：第1集 魔王演技
 Type:      video
 Streams:   # All available quality
     [1]  -------------------
     Quality:         640x360
     Size:            63.14 MiB (66209652 Bytes)
     # download with: annie -f 1 "URL"

     [2]  -------------------
     Quality:         896x504
     Size:            101.58 MiB (106518356 Bytes)
     # download with: annie -f 2 "URL"

     [96]  -------------------
     Quality:         384x216
     Size:            31.95 MiB (33499156 Bytes)
     # download with: annie -f 96 "URL"

     [21]  -------------------
     Quality:         896x504
     Size:            123.96 MiB (129982448 Bytes)
     # download with: annie -f 21 "URL"

     [17]  -------------------
     Quality:         1280x720
     Size:            154.63 MiB (162143796 Bytes)
     # download with: annie -f 17 "URL"

     [default]  -------------------
     Quality:         1280x720
     Size:            163.87 MiB (171826548 Bytes)
     # download with: annie -f default "URL"
```

```
>annie -i http://www.iqiyi.com/v_19rr1u4xrw.html

 Site:      爱奇艺 iqiyi.com
 Title:     异界少女召唤术 第1集
 Type:      video
 Streams:   # All available quality
     [96]  -------------------
     Quality:         384x216
     Size:            9.94 MiB (10417832 Bytes)
     # download with: annie -f 96 "URL"

     [2]  -------------------
     Quality:         896x504
     Size:            36.61 MiB (38392044 Bytes)
     # download with: annie -f 2 "URL"

     [default]  -------------------
     Quality:         1920x1080
     Size:            64.23 MiB (67351564 Bytes)
     # download with: annie -f default "URL"

     [1]  -------------------
     Quality:         640x360
     Size:            19.23 MiB (20163000 Bytes)
     # download with: annie -f 1 "URL"

     [17]  -------------------
     Quality:         1280x720
     Size:            40.07 MiB (42018940 Bytes)
     # download with: annie -f 17 "URL"

     [5]  -------------------
     Quality:         1920x1080
     Size:            116.00 MiB (121632240 Bytes)
     # download with: annie -f 5 "URL"

     [4]  -------------------
     Quality:         1280x720
     Size:            61.50 MiB (64492648 Bytes)
     # download with: annie -f 4 "URL"

     [21]  -------------------
     Quality:         896x504
     Size:            32.16 MiB (33718364 Bytes)
     # download with: annie -f 21 "URL"
```
如上，这是同一部作品的大陆版，没有会员所以只能解析到试看部分，但是有1080P。对应TW版，可以解析到完整版，但是没有1080P，而网页端两者都有1080P。请问TW版是否也能解析到1080P，谢谢。

**Comment by wellos99** [comment]
我有tw iqiyi的会员，要吗？
