### ISSUE TITLE
[YouKu]优酷视频下载出错

### ISSUE THREAD

**Issue by iqinqin** [iawia002/annie#229]
`F:\Vdownload>annie - i https://v.youku.com/v_show/id_XMTM2MTIwODM4MA
2018/08/18 16:57:47 parse -: invalid URI for request`

**Comment by iawia002** [comment]
你这个 - 和 i 之间有空格

**Comment by iqinqin** [comment]
> F:\Vdownload>annie -i https://v.youku.com/v_show/id_XMTM2MTIwODM4MA
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Youku(0xc04200a2a0, 0x2d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youku.go:151 +0x3cc
main.download(0xc04200a2a0, 0x2d)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:73 +0x47d
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:136 +0xe7

**Comment by iawia002** [comment]
URL 先加下 `.html`，这个正则我再改改

```console
$ annie https://v.youku.com/v_show/id_XMTM2MTIwODM4MA.html

 Site:      优酷 youku.com
 Title:     大好时光 01
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         mp4hd2 1104x616 国语
     Size:            392.72 MiB (411792581 Bytes)
     # download with: annie "URL"

 21.50 MiB / 392.72 MiB [=>--------------------------]   5.47% 6.88 MiB/s 00m53s
```
