### ISSUE TITLE
Bilibil视频下载失败

### ISSUE THREAD

**Issue by 1132719438** [iawia002/annie#236]
version: 0.7.12

URL: https://www.bilibili.com/video/av3853798

视频下载失败，怀疑是视频标题特殊字符造成：

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.Download(0xc042078030, 0x28)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:142 +0xa0e
main.download(0xc042078030, 0x28)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:64 +0x804
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:131 +0xe7
```

**Comment by iawia002** [comment]
是这个视频的问题，你登录了才能看到，所以要带你登录过的 cookies 访问就行

```console
$ annie -c ~/Desktop/cookies.txt -i av3853798

 Site:      哔哩哔哩 bilibili.com
 Title:     【游戏发展史】第四世代之CD-Rom²与H Game
 Type:      video
 Streams:   # All available quality
     [default]  -------------------
     Quality:         高清 1080P
     Size:            76.09 MiB (79785506 Bytes)
     # download with: annie "URL"

     [32]  -------------------
     Quality:         清晰 480P
     Size:            56.51 MiB (59252740 Bytes)
     # download with: annie -f 32 "URL"

     [48]  -------------------
     Quality:         高清 720P
     Size:            56.32 MiB (59060356 Bytes)
     # download with: annie -f 48 "URL"

     [16]  -------------------
     Quality:         流畅 360P
     Size:            21.00 MiB (22019871 Bytes)
     # download with: annie -f 16 "URL"
```

**Comment by iawia002** [comment]
#208
