### ISSUE TITLE
源代码没有更新吗

### ISSUE THREAD

**Issue by moyokoo** [iawia002/annie#306]
微拍下载那部分 我用你提供的库是可以下载成功的 
但是下载来的源码 自己测试是失败的 
视频地址  https://www.miaopai.com/show/o2e0Ml8SixGTQmERLF30Isd56ahnndpfkeeg3A__.htm

**Comment by moyokoo** [comment]
下载了最新的代码 
测试的结果是 原来老的视频解析失效了  比如这个
http://n.miaopai.com/media/qVWj3dVK2oSxtW~vSq2tGeBKPE--tPSp

**Comment by SeaHOH** [comment]
确实，非`http://n.miaopai.com/media/*`格式的地址有部分会重定向过来。

**Comment by moyokoo** [comment]
是要根据重定向后的地址进行解析吗

**Comment by SeaHOH** [comment]
不用，直接的。

**Comment by moyokoo** [comment]
是要更新版本么  
```
annie -v

annie: version 0.8.2, A fast, simple and clean video downloader.
```

```
annie -i https://www.miaopai.com/show/o2e0Ml8SixGTQmERLF30Isd56ahnndpfkeeg3A__.htm
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/miaopai.Download(0x7ffeefbffb41, 0x49, 0x13411d0, 0x7, 0xffffffffffffffff, 0x0, 0x0)
	/private/tmp/annie-20181014-86441-ja69cv/annie-0.8.2/src/github.com/iawia002/annie/extractors/miaopai/miaopai.go:22 +0x540
main.download(0x7ffeefbffb41, 0x49)
	/private/tmp/annie-20181014-86441-ja69cv/annie-0.8.2/src/github.com/iawia002/annie/main.go:125 +0x997
main.main()
	/private/tmp/annie-20181014-86441-ja69cv/annie-0.8.2/src/github.com/iawia002/annie/main.go:195 +0x105


```

**Comment by iawia002** [comment]
我还没发新版本，如果你有 Go 环境的话，可以直接 go get 更新 master 的代码

**Comment by iawia002** [comment]
0.8.3
