### ISSUE TITLE
youtube 视频无法下载

### ISSUE THREAD

**Issue by yuanwenjian** [iawia002/annie#309]
您好，
youtube视频使用代理报错，下面是我的命令及报错信息
```bash    
annie -s 127.0.0.1:1080 -i 'https://www.youtube.com/watch?v=2eHezHZ1Z5c'

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1244e70]

goroutine 1 [running]:
github.com/iawia002/annie/request.Request(0x132434f, 0x3, 0xc42007e180, 0x57, 0x0, 0x0, 0xc4201a7820, 0x2b)
	/private/tmp/annie-20180816-11637-1clo59t/annie-0.7.15/src/github.com/iawia002/annie/request/request.go:97 +0xb40
github.com/iawia002/annie/request.Get(0xc42007e180, 0x57, 0x132ed2b, 0x17, 0xc4201a7820, 0x0, 0x0)
	/private/tmp/annie-20180816-11637-1clo59t/annie-0.7.15/src/github.com/iawia002/annie/request/request.go:129 +0xb7
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0x7ffeefbffa0b, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/annie-20180816-11637-1clo59t/annie-0.7.15/src/github.com/iawia002/annie/extractors/youtube/youtube.go:106 +0x17c
github.com/iawia002/annie/extractors/youtube.Download(0x7ffeefbffa0b, 0x2b)
	/private/tmp/annie-20180816-11637-1clo59t/annie-0.7.15/src/github.com/iawia002/annie/extractors/youtube/youtube.go:69 +0x440
main.download(0x7ffeefbffa0b, 0x2b)
	/private/tmp/annie-20180816-11637-1clo59t/annie-0.7.15/src/github.com/iawia002/annie/main.go:75 +0x463
main.main()
	/private/tmp/annie-20180816-11637-1clo59t/annie-0.7.15/src/github.com/iawia002/annie/main.go:136 +0xe0
```

电脑是mac,代理开了，浏览器可以正常访问,请问是我代理配置有问题么？谢谢啦

**Comment by iqinqin** [comment]
可能是有ip限制，或是要登录才能下载
