### ISSUE TITLE
优酷下载失败

### ISSUE THREAD

**Issue by xiiatuuo** [iawia002/annie#35]
annie https://v.youku.com/v_show/id_XMzQ2NzU2NTg0MA.html -d
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.genData(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6, 0x8, ...)
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youku.go:83 +0x4e7
github.com/iawia002/annie/extractors.Youku(0x7fff88f748d3, 0x32, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youku.go:111 +0x185
main.main()
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:55 +0x247

**Comment by xiiatuuo** [comment]
annie -v
annie: version 0.5.0, A simple and clean video downloader.

**Comment by iawia002** [comment]
@xiiatuuo 稳定复现吗

```
   Site:   优酷 youku.com
  Title:   看傻! 喵星人的N种打开方式!
   Type:   video
Quality:   mp4hd2v2 1280x720
   Size:   42.09 MiB (44133241 Bytes)

 42.09 MiB / 42.09 MiB [=================================] 100.00% 9.16 MiB/s 4s
Merging video parts into 看傻! 喵星人的N种打开方式!.mp4
```

**Comment by xiiatuuo** [comment]
@iawia002 稳定复现

**Comment by iawia002** [comment]
@xiiatuuo 下载其他视频有没有问题

**Comment by xiiatuuo** [comment]
@iawia002 下bilibili没问题

**Comment by iawia002** [comment]
@xiiatuuo 我的意思是下载其他优酷视频有没有问题

**Comment by iawia002** [comment]
用最新版来试

**Comment by xiiatuuo** [comment]
annie https://v.youku.com/v_show/id_XMzQ2NzU2NTg0MA.html -d

 Site:      优酷 youku.com
 Title:     看傻! 喵星人的N种打开方式!
 Type:      video
 Stream:
     [default]  -------------------
     Size:            0.00 MiB (0 Bytes)
     # download with: annie -f default "URL"

 0 B / ? [-------------------------------------------------------------------------------------------------------------------------------------------------------------=] 0s
Merging video parts into 看傻! 喵星人的N种打开方式!.mp4
2018/03/27 14:06:32 exit status 1

最新版也不行

**Comment by iawia002** [comment]
看起来你完全没有拿到数据哎，你重试几次有用吗

```
 Site:      优酷 youku.com
 Title:     看傻! 喵星人的N种打开方式!
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         mp4hd2v2 1280x720
     Size:            42.09 MiB (44133241 Bytes)
     # download with: annie -f default "URL"

 13.11 MiB / 42.09 MiB [==========>----------------------]  31.14% 7.49 MiB/s 3s
```

**Comment by xiiatuuo** [comment]
不行，这是哪一步有问题呢，是不是ip被bang了之类

**Comment by iawia002** [comment]
优酷没有报“客户端无权播放”这个错，应该是其他错误，但我复现不了就不知道是什么错。你有代理吗，挂代理试试是不是 IP 被 ban 了

**Comment by iawia002** [comment]
@xiiatuuo 试一下 0.6.4 能不能解决你的问题

**Comment by sunfmin** [comment]
```

$ annie https://v.youku.com/v_show/id_XMzM2NTY4MjEyMA==.html

 Site:      优酷 youku.com
 Title:     咖啡风暴
 Type:      video
 Stream:   
     [default]  -------------------
     Quality:         mp4hd3 1920x806
     Size:            1237.68 MiB (1297798081 Bytes)
     # download with: annie -f default "URL"

 0 B / 1.21 GiB [------------------------------------------------------------------------------------------------------]   0.00%2018/04/09 09:50:41 
2018/04/09 09:50:41 
panic: Get : unsupported protocol scheme ""

goroutine 57 [running]:
github.com/iawia002/annie/request.Request(0x1312752, 0x3, 0x0, 0x0, 0x0, 0x0, 0xc420045cf0, 0x0)
	/private/tmp/annie-20180405-22689-1t7dolr/annie-0.6.4/src/github.com/iawia002/annie/request/request.go:87 +0xb78
github.com/iawia002/annie/downloader.FormatData.urlSave(0xc420173500, 0x32, 0x43, 0xc4203056f0, 0xf, 0x4d5ad3c1, 0x0, 0x0, 0x1f0b8db, 0xc42023a8a1, ...)
	/private/tmp/annie-20180405-22689-1t7dolr/annie-0.6.4/src/github.com/iawia002/annie/downloader/downloader.go:105 +0x3d6
github.com/iawia002/annie/downloader.VideoData.Download.func1(0xc420305850, 0xc420477770, 0x0, 0x0, 0x1f0b8db, 0xc42023a8a1, 0x3, 0x7ffeefbff66e, 0x34, 0xc4203058c0, ...)
	/private/tmp/annie-20180405-22689-1t7dolr/annie-0.6.4/src/github.com/iawia002/annie/downloader/downloader.go:214 +0xed
created by github.com/iawia002/annie/downloader.VideoData.Download
	/private/tmp/annie-20180405-22689-1t7dolr/annie-0.6.4/src/github.com/iawia002/annie/downloader/downloader.go:212 +0x68d
panic: Get : unsupported protocol scheme ""

goroutine 103 [running]:
github.com/iawia002/annie/request.Request(0x1312752, 0x3, 0x0, 0x0, 0x0, 0x0, 0xc420041cf0, 0x0)
	/private/tmp/annie-20180405-22689-1t7dolr/annie-0.6.4/src/github.com/iawia002/annie/request/request.go:87 +0xb78
github.com/iawia002/annie/downloader.FormatData.urlSave(0xc420173500, 0x32, 0x43, 0xc4203056f0, 0xf, 0x4d5ad3c1, 0x0, 0x0, 0x31ae187, 0xc42023a8a1, ...)
	/private/tmp/annie-20180405-22689-1t7dolr/annie-0.6.4/src/github.com/iawia002/annie/downloader/downloader.go:105 +0x3d6
github.com/iawia002/annie/downloader.VideoData.Download.func1(0xc420305850, 0xc420477770, 0x0, 0x0, 0x31ae187, 0xc42023a8a1, 0x3, 0x7ffeefbff66e, 0x34, 0xc420305d60, ...)
	/private/tmp/annie-20180405-22689-1t7dolr/annie-0.6.4/src/github.com/iawia002/annie/downloader/downloader.go:214 +0xed
created by github.com/iawia002/annie/downloader.VideoData.Download
	/private/tmp/annie-20180405-22689-1t7dolr/annie-0.6.4/src/github.com/iawia002/annie/downloader/downloader.go:212 +0x68d


```

**Comment by iawia002** [comment]
@sunfmin 这是 VIP 才能看的吧，优酷只返回了前三段的下载地址，后面的都没返，所以报错了

**Comment by sunfmin** [comment]
可能是VIP的问题

**Comment by sunfmin** [comment]
另一个不是vip的视频的问题

```
$ annie https://v.youku.com/v_show/id_XMjk3NDI1MTcwNA==.html

 Site:      优酷 youku.com
 Title:     京城81号2
 Type:      video
 Stream:   
     [default]  -------------------
     Quality:         mp4hd3 1920x806
     Size:            825.71 MiB (865818970 Bytes)
     # download with: annie -f default "URL"

 575.49 MiB / 825.71 MiB [====================================>----------------]  69.70% 14.93 MiB/s 16s2018/04/09 14:07:05 Error while downloading: http://vali-dns.cp31.ott.cibntv.net/6981D590494D3B7176788230F8/0300802B1E59A8CDCAC028011BA6A93EF4CA28-F0D6-EB0B-B113-91BC64CA4181.flv?ccode=0502&duration=137&expire=18000&psid=bc4df2d91074e45a1137f0a952f0b65d&sp=&ups_client_netip=b7814734&ups_ts=1523253986&ups_userid=&utid=4vBRE1hWXjECAbeBRzRvRpsf&vid=XMjk3NDI1MTcyMA%3D%3D&vkey=Be9fd545a26cdc57a5a4554f58e266e66&s=44d2e1904a6211e69e2a, unexpected EOF
```

**Comment by iawia002** [comment]
> unexpected EOF

这个错误出过几次（#82），还没找到问题的根源

**Comment by sunfmin** [comment]
出现了一次，我第二次运行同样的命令，就下载成功了。

**Comment by iawia002** [comment]
@xiiatuuo 还有反馈吗，我要关 issue 了哦
