### ISSUE TITLE
[bilibili] 解析异常  

### ISSUE THREAD

**Issue by 123ojp** [iawia002/annie#365]
平常使用沒問題
今日使用時
`annie "https://www.bilibili.com/bangumi/play/ep72043"`
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.bilibiliDownload(0x7ffd804387ee, 0x2d, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:242 +0x1004
github.com/iawia002/annie/extractors/bilibili.Download(0x7ffd804387ee, 0x2d, 0x7ffd804387fa, 0x8, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:155 +0xc6d
main.download(0x7ffd804387ee, 0x2d)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:107 +0xb8e
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:211 +0x11a
```
是bilibili換方式了嗎
版本號:
`annie: version 0.8.5, A fast, simple and clean video downloader.`

**Comment by mengyyy** [comment]
season_type 不在了……
下番剧我临时改了一下
```
	var seasonType string
	if options.Bangumi {
		seasonType = "1"//utils.MatchOneOf(html, `"season_type":(\d+)`)[1]
	}
```

**Comment by iawia002** [comment]
你带上登录过的 cookies 就可以了，@mengyyy 的方法也可以，我呆会儿兼容一下

**Comment by iawia002** [comment]
0.9.1
