### ISSUE TITLE
昨天更新以后，bilibili的av可以下载了，但是番剧好像不行了

### ISSUE THREAD

**Issue by zpkosmos** [iawia002/annie#391]
D:\bilibilidownload\video>annie https://www.bilibili.com/bangumi/play/ss25681
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x747b1b, 0x19, 0xc00000cba0, 0x20, 0x73c3e0, 0x5, 0xc0001ce240, 0x0, 0x0, 0x0, ...)
        c:/go/Go_WorkSpace/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x1588
main.download(0xc000086030, 0x2d)
        c:/go/Go_WorkSpace/src/github.com/iawia002/annie/main.go:163 +0x44f
main.main()
        c:/go/Go_WorkSpace/src/github.com/iawia002/annie/main.go:217 +0x121

不会是我命令弄错了吧？难道要登陆吗？

**Comment by iawia002** [comment]
你先带上登录过的 cookies 下载吧，这个问题我空了再看一下

```console
$ annie -c ~/Downloads/cookies.txt -i https://www.bilibili.com/bangumi/play/ss25681

 Site:      哔哩哔哩 bilibili.com
 Title:     JOJO的奇妙冒险 黄金之风：第1话 黄金体验 (Gold Experience)
 Type:      video
 Streams:   # All available quality
     [112]  -------------------
     Quality:         高清 1080P+
     Size:            731.14 MiB (766658633 Bytes)
     # download with: annie -f 112 ...

     [80]  -------------------
     Quality:         高清 1080P
     Size:            386.23 MiB (404995734 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            298.56 MiB (313062688 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            195.46 MiB (204955650 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            82.59 MiB (86597398 Bytes)
     # download with: annie -f 16 ...
```

**Comment by hgelong** [comment]
现在清晰度只有360p了

**Comment by anonymity12** [comment]
我有同样的问题
```
goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x134c488, 0x19, 0xc000302000, 0xa1, 0x1341c3a, 0x5, 0xc0002a01e0, 0x0, 0x0, 0x0, ...)
	/private/tmp/annie-20181124-53134-rlcpgc/annie-0.8.5/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x1578
```
360p也可以啊，请问是如何下载360p呢？

**Comment by hgelong** [comment]
> 我有同样的问题
> 
> ```
> goroutine 1 [running]:
> github.com/iawia002/annie/downloader.Download(0x134c488, 0x19, 0xc000302000, 0xa1, 0x1341c3a, 0x5, 0xc0002a01e0, 0x0, 0x0, 0x0, ...)
> 	/private/tmp/annie-20181124-53134-rlcpgc/annie-0.8.5/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x1578
> ```
> 360p也可以啊，请问是如何下载360p呢？

我列出清晰度，发现只有360p这一栏，但没出现报错，可以下载。

**Comment by hgelong** [comment]
> 我有同样的问题
> 
> ```
> goroutine 1 [running]:
> github.com/iawia002/annie/downloader.Download(0x134c488, 0x19, 0xc000302000, 0xa1, 0x1341c3a, 0x5, 0xc0002a01e0, 0x0, 0x0, 0x0, ...)
> 	/private/tmp/annie-20181124-53134-rlcpgc/annie-0.8.5/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x1578
> ```
> 360p也可以啊，请问是如何下载360p呢？

我发现问题了：ss的会出现这个错误，而ep开头的会只有360p清晰度。切换成ep就可以下360p了
例如作者给的：https://www.bilibili.com/bangumi/play/ss25681
换成：https://www.bilibili.com/bangumi/play/ep250611

**Comment by CyshallChan** [comment]
同样问题+1，以下是报错信息：

----------------------------------------------------------------------------------------------------------
annie -i -p https://www.bilibili.com/video/av39031994
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x745841, 0x19, 0xc0002302a0, 0x63, 0x73a0e0, 0x5, 0xc0001625d0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x1631
main.download(0xc000074090, 0x29)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:163 +0x44f
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:217 +0x121
--------------------------------------------------------------------------------------------------------

**Comment by iawia002** [comment]
要么就登录之后带上登录过的 cookies 下载，不想登录的话就用番剧真正的地址 ep... 这种

@CyshallChan 你是什么版本的？我试了一下没问题啊

```
 Site:      哔哩哔哩 bilibili.com
 Title:     高中数学-高一、高二、高三【专题复习】（基础篇） 12.1 绝对值不等式
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            270.37 MiB (283506401 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            216.74 MiB (227270103 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            139.70 MiB (146489201 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            71.54 MiB (75016585 Bytes)
     # download with: annie -f 16 ...


 Site:      哔哩哔哩 bilibili.com
 Title:     高中数学-高一、高二、高三【专题复习】（基础篇） 12.2 证明不等式的基本方法
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            144.80 MiB (151834738 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            119.96 MiB (125791994 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            77.68 MiB (81454703 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            43.36 MiB (45466869 Bytes)
     # download with: annie -f 16 ...
```

**Comment by CyshallChan** [comment]
> 要么就登录之后带上登录过的 cookies 下载，不想登录的话就用番剧真正的地址 ep... 这种
> 
> @CyshallChan 你是什么版本的？我试了一下没问题啊
> 
> ```
>  Site:      哔哩哔哩 bilibili.com
>  Title:     高中数学-高一、高二、高三【专题复习】（基础篇） 12.1 绝对值不等式
>  Type:      video
>  Streams:   # All available quality
>      [80]  -------------------
>      Quality:         高清 1080P
>      Size:            270.37 MiB (283506401 Bytes)
>      # download with: annie -f 80 ...
> 
>      [64]  -------------------
>      Quality:         高清 720P
>      Size:            216.74 MiB (227270103 Bytes)
>      # download with: annie -f 64 ...
> 
>      [32]  -------------------
>      Quality:         清晰 480P
>      Size:            139.70 MiB (146489201 Bytes)
>      # download with: annie -f 32 ...
> 
>      [16]  -------------------
>      Quality:         流畅 360P
>      Size:            71.54 MiB (75016585 Bytes)
>      # download with: annie -f 16 ...
> 
> 
>  Site:      哔哩哔哩 bilibili.com
>  Title:     高中数学-高一、高二、高三【专题复习】（基础篇） 12.2 证明不等式的基本方法
>  Type:      video
>  Streams:   # All available quality
>      [80]  -------------------
>      Quality:         高清 1080P
>      Size:            144.80 MiB (151834738 Bytes)
>      # download with: annie -f 80 ...
> 
>      [64]  -------------------
>      Quality:         高清 720P
>      Size:            119.96 MiB (125791994 Bytes)
>      # download with: annie -f 64 ...
> 
>      [32]  -------------------
>      Quality:         清晰 480P
>      Size:            77.68 MiB (81454703 Bytes)
>      # download with: annie -f 32 ...
> 
>      [16]  -------------------
>      Quality:         流畅 360P
>      Size:            43.36 MiB (45466869 Bytes)
>      # download with: annie -f 16 ...
> ```

我以为我是最新版，结果发现不是，更新了一下就好- - 。

**Comment by julianlouis** [comment]
我想问一下 如何带cookie下载 因为我下的东西需要大会员然后只能下载六分钟 多谢
