### ISSUE TITLE
panic: runtime error: index out of range bug on certain Bilibili playlist

### ISSUE THREAD

**Issue by fireattack** [iawia002/annie#455]
```
[***]>annie -p  https://www.bilibili.com/video/av1747536

 Site:      哔哩哔哩 bilibili.com
 Title:     Anime mashite 1124 雨宫天X伊藤美来+未公开部分 本篇
 Type:      video
 Stream:
     [80]  -------------------
     Quality:         高清 1080P
     Size:            296.19 MiB (310575775 Bytes)
     # download with: annie -f 80 ...

 296.19 MiB / 296.19 MiB [==============================================================================] 100.00% 1.20 MiB/s 4m5s
Merging video parts into Anime mashite 1124 雨宫天X伊藤美来+未公开部分 本篇.mp4
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x748b5f, 0x19, 0xc0002da200, 0x73, 0x73d406, 0x5, 0xc000286120, 0x0, 0x0, 0x0, ...)

        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:188 +0x1656
main.download(0xc00000c2a0, 0x28)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:167 +0x45e
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:221 +0x121

[***]>
```

**Comment by fireattack** [comment]
我才发现那个视频p2被和谐了囧……

不过也许加个提示而不是直接error好点？

**Comment by iawia002** [comment]
恩那个视频本来被和谐了

不好提示，我不能分辨它是被和谐了还是本来就不存在
