### ISSUE TITLE
linux下部分报错,windows不报错

### ISSUE THREAD

**Issue by Crazp** [iawia002/annie#625]
`annie.exe -i http://www.iqiyi.com/v_19rr9stk38.html
`
 ```
Site:      爱奇艺 iqiyi.com
 Title:     男生女生向前冲第八季：女生队奋发图强 力压男队
 Type:      video
 Streams:   # All available quality
```

```
root@sd-157949:~# annie -i http://www.iqiyi.com/v_19rr9stk38.html
panic: runtime error: index out of range
```

```
goroutine 1 [running]:
github.com/iawia002/annie/extractors/iqiyi.Extract(0x7ffc6223130a, 0x26, 0x7bcafd, 0x5, 0xffffffffffffffff, 0xc0000695f0, 0x3)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/iqiyi/iqiyi.go:160 +0xfc8
main.download(0x7ffc6223130a, 0x26, 0x7da948)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:129 +0x9b2
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:238 +0x176

```

**下载win64的到linux，用wine annie.exe -i  同样错误。源码build也是一个结果。**

linux 的 annie 部分报错，win下基本无错误。linux wine exe 报错。怀疑从shell 接收string有问题。

**Comment by Crazp** [comment]
确认乐，IP问题。国外IP不行
