### ISSUE TITLE
bilibili番剧获取信息异常

### ISSUE THREAD

**Issue by sorakirahk** [iawia002/annie#678]
annie版本0.9.8
系统：win7

https://www.bilibili.com/bangumi/play/ep320760
只能获取第一集

```
annie -c cookie.txt -i ep320760

Site:      哔哩哔哩 bilibili.com
Title:     孤独的美食家 第八季：第1集 神奈川县横滨中华街的中华煲仔饭和鲜虾云吞面
Type:      video
Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            430.76 MiB (451689505 Bytes)
     # download with: annie -f 80 ...
```
获取下一集就报错
```
annie -c cookie.txt -i ep320761

panic: runtime error: index out of range
goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x7c8079, 0x19, 0xc0002762a0, 0x60
, 0x7bc24a, 0x5, 0xc00027c1e0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/download
er.go:196 +0x188e
main.download(0xc00000e360, 0x2e, 0x7db168)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:184 +0x448
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:238 +0x17d
```
-p 命令也是只能获取到第一集

测试了下我的cookie正常，会员也没问题。测试视频https://www.bilibili.com/video/av77980934 
annie正常工作
```
annie -c cookie.txt -i https://www.bilibili.com/video/av77980934

Site:      哔哩哔哩 bilibili.com
Title:     【随义】《黑暗之魂2：原罪学者》全收集猛男攻略流程解说【完结】 P1 P1
一线天森林
Type:      video
Streams:   # All available quality
     [116]  -------------------
     Quality:         高清 1080P60
     Size:            1753.80 MiB (1838990226 Bytes)
     # download with: annie -f 116 ...
```

**Comment by Half9000** [comment]
try 0.10.3
