### ISSUE TITLE
输入含protocol的不支持地址会出invalid memory address or nil pointer dereference error而非显示“不支持”信息

### ISSUE THREAD

**Issue by fireattack** [iawia002/annie#754]
Expected:

```
G:\>annie google.com
Downloading [36mgoogle.com[0m error:
[31mparse google.com: invalid URI for request[0m
```
Unexpected:

```
G:\>annie "https://google.com"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x8b828c]

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Extract(0xc000070140, 0x12, 0x0, 0x0, 0x0, 0x1, 0x0, 0xa, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/extractors.go:104 +0x2fc
main.download(0xc000070140, 0x12, 0x1, 0x1)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:131 +0x194
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:253 +0x274

```

版本：built from `master`

**Comment by snylonue** [comment]
https://github.com/iawia002/annie/blob/67298d55aaf43d840b8d7283b0ac99736173d285/extractors/extractors.go#L103-L104
这里没判断 domain 是否存在
