### ISSUE TITLE
http://ip:port urls problem?

### ISSUE THREAD

**Issue by mathieu-aubin** [iawia002/annie#76]
Running the following seem to result in an error

`./annie -d http://3.18.168.212:7734/file.mp3`

```
annie: version 0.6.3, A fast, simple and clean video downloader.

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/utils.Domain(0x7ffefaa7744d, 0x13, 0xc420142180, 0x0)
	/XXXXXXX/go/src/github.com/iawia002/annie/utils/utils.go:58 +0xa3
main.main()
	/XXXXXXX/go/src/github.com/iawia002/annie/main.go:54 +0x1ca
```

GOOS=linux / GOARCH=amd64 / CGO_ENABLED=0 (if thats of any help)

Thanks

**Comment by iawia002** [comment]
yeah, that's a bug, I did not consider the URL with IP address
