### ISSUE TITLE
bilibili下载大合集报错

### ISSUE THREAD

**Issue by mengdodo** [iawia002/annie#782]
annie -i -p https://www.bilibili.com/video/BV1d4411i7wD\?from\=search\&seid\=1635873361310897271

```

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x13e39ff, 0x19, 0xc000c06d80, 0x35, 0x13d87d5, 0x5, 0xc00092e960, 0x0, 0x0, 0x0, ...)
	/private/tmp/annie-20200204-94559-kdq9vh/annie-0.9.8/downloader/downloader.go:196 +0x1811
main.download(0x7ffeefbff43c, 0x50, 0x7ffeefbff43c)
	/private/tmp/annie-20200204-94559-kdq9vh/annie-0.9.8/main.go:184 +0x440
main.main()
	/private/tmp/annie-20200204-94559-kdq9vh/annie-0.9.8/main.go:238 +0x16d
```

**Comment by woshichuanqilz** [comment]
我也是这个问题现在解决了没?

**Comment by mengdodo** [comment]
> 我也是这个问题现在解决了没?
我换了一个可行
```
you-get --playlist 'https://www.bilibili.com/video/av51636878/'
```

**Comment by delusionxb** [comment]
> > 我也是这个问题现在解决了没?
> > 我换了一个可行
> 
> ```
> you-get --playlist 'https://www.bilibili.com/video/av51636878/'
> ```

you-get我用着也是412
