### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Sesprie** [iawia002/annie#789]
事情经过是这样的，
开始我执行（后来发现是网络的原因）
```
annie https://v.qq.com/x/page/o0772kqh5iv.html
```
然后没有反映，我新开了一个命令行，执行
```
annie https://b23.tv/BV1bs411x7J4
```
报错如下
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x8ba14c]

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Extract(0xc00007c140, 0x1b, 0x0, 0x0, 0x0, 0x1, 0x0, 0xa, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/extractors.go:104 +0x2fc
main.download(0xc00007c140, 0x1b, 0x1, 0x1)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:131 +0x194
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:253 +0x274
```

annie的版本
```
annie: version 0.10.3, A fast, simple and clean video downloader.
```

**Comment by Sesprie** [comment]
刚才又试了一下，是不支持`https://b23.tv`导致的，跳转后的bilibili下载链接正常，
