### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by johnny-silverhand** [iawia002/annie#814]
`annie https://www.dailymotion.com/video/x7whxp5`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8b8265]

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Extract(0x7ffc77ea85de, 0x29, 0x0, 0x0, 0x0, 0x1, 0x0, 0xa, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/extractors.go:104 +0x2f5
main.download(0x7ffc77ea85de, 0x29, 0x1, 0x1)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:131 +0x18d
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:253 +0x26d
```

**Comment by snylonue** [comment]
[This site is not supported](https://github.com/iawia002/annie#supported-sites)
and see #754 about the confusing error message

**Comment by johnny-silverhand** [comment]
> 
> 
> [This site is not supported](https://github.com/iawia002/annie#supported-sites)
> and see #754 about the confusing error message

I hope that in the future there will be a check on the list of supported sites. And instead of panic, write human readable an errors.
