### ISSUE TITLE
youtube 获取不到1080p的视频

### ISSUE THREAD

**Issue by sherylynn** [iawia002/annie#96]
用you-get可以-i url 发现1080p的视频
同一个地址 annie -i url就发现不了

url: "https://www.youtube.com/watch?v=ifn5noo2cYQ"
命令: 
annie -i "https://www.youtube.com/watch?v=ifn5noo2cYQ"
you-get -i "https://www.youtube.com/watch?v=ifn5noo2cYQ"

**Comment by Justsoos** [comment]
添加点信息，win10上无法使用annie下载u2b：
这是用 proxifier代理，得到的信息，后面大段重复就没copy了
```
[time-stamp:25] annie.exe *64 - www.youtube.com:443 open through proxy 127.0.0.1:1080 SOCKS5
[time-stamp:26] annie.exe *64 - r6---sn-n4v7sn7y.googlevideo.com:443 open through proxy 127.0.0.1:1080 SOCKS5
[time-stamp:27] annie.exe *64 - r6---sn-n4v7sn7y.googlevideo.com:443 close, 1362 bytes (1.33 KB) sent, 7297 bytes (7.12 KB) received, lifetime 00:01
[time-stamp:27] annie.exe *64 - r6---sn-n4v7sn7y.googlevideo.com:443 open through proxy 127.0.0.1:1080 SOCKS5
[time-stamp:36] chrome.exe *64 - webim.tim.qq.com:443 close, 2435 bytes (2.37 KB) sent, 4999 bytes (4.88 KB) received, lifetime 00:28
[time-stamp:37] annie.exe *64 - r6---sn-n4v7sn7y.googlevideo.com:443 close, 205 bytes sent, 0 bytes received, lifetime 00:10
[time-stamp:37] chrome.exe *64 - webim.tim.qq.com:443 open through proxy 127.0.0.1:1080 SOCKS5
[time-stamp:37] annie.exe *64 - www.youtube.com:443 close, 1644 bytes (1.60 KB) sent, 77316 bytes (75.5 KB) received, lifetime 00:12
[time-stamp:38] wv2ray.exe *64 - 127.8.0.2:5228 error: Cannot connect to placeholder (fake) IP address. It's recomended to restart the application.
[time-stamp:39] wv2ray.exe *64 - 127.8.0.2:5228 error: Cannot connect to placeholder (fake) IP address. It's recomended to restart the application.
[time-stamp:40] wv2ray.exe *64 - 127.8.0.2:5228 error: Cannot connect to placeholder (fake) IP address. It's recomended to restart the application
```

这是控制台输出：
```
# annie.exe https://www.youtube.com/watch?v=w7CisyOOB1o
2018/05/12 00:11:37 https://r6---sn-n4v7sn7y.googlevideo.com/videoplayback?dur=0.000&mv=m&mt=1523518417&ms=au%2Crdu&mn=sn-n4v7sn7y%2Csn-n4v7knls&signature=765476795155C9DC2ECE5EF97C76E0D6A6F6A4AE.3815CE22F767F1C0848EDD4BD1E94CFFEF3AD35F&mm=31%2C29&itag=43&gir=yes&clen=27098181&mime=video%2Fwebm&fvip=1&ipbits=0&requiressl=yes&ratebypass=yes&pl=19&initcwndbps=766250&source=youtube&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&c=WEB&expire=1523540066&id=o-AKVXItX5-Pp40HFYDup3jGqOHJjX_v_cIMEepeY2zr5f&lmt=1514276676144139&ip=137.175.66.78&key=yt6&ei=AgzPWu2YC8W--AP56IKoAQ
panic: Get https://r6---sn-n4v7sn7y.googlevideo.com/videoplayback?dur=0.000&mv=m&mt=1523518417&ms=au%2Crdu&mn=sn-n4v7sn7y%2Csn-n4v7knls&signature=765476795155C9DC2ECE5EF97C76E0D6A6F6A4AE.3815CE22F767F1C0848EDD4BD1E94CFFEF3AD35F&mm=31%2C29&itag=43&gir=yes&clen=27098181&mime=video%2Fwebm&fvip=1&ipbits=0&requiressl=yes&ratebypass=yes&pl=19&initcwndbps=766250&source=youtube&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&c=WEB&expire=1523540066&id=o-AKVXItX5-Pp40HFYDup3jGqOHJjX_v_cIMEepeY2zr5f&lmt=1514276676144139&ip=137.175.66.78&key=yt6&ei=AgzPWu2YC8W--AP56IKoAQ: net/http: TLS handshake timeout

goroutine 1 [running]:
github.com/iawia002/annie/request.Request(0x70a88c, 0x3, 0xc0424042c0, 0x293, 0x0, 0x0, 0xc04217f970, 0x20)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:87 +0xb7f
github.com/iawia002/annie/request.Headers(0xc0424042c0, 0x293, 0xc04206e030, 0x2b, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:131 +0x127
github.com/iawia002/annie/request.Size(0xc0424042c0, 0x293, 0xc04206e030, 0x2b, 0x29)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:138 +0x54
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0xc04206e030, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:113 +0x49d
github.com/iawia002/annie/extractors/youtube.Download(0xc04206e030, 0x2b)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:65 +0x30b
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:67 +0x40e
```
